export const BROWSING_HISTORY_ADD_REQUEST = 'BROWSING_HISTORY_ADD_REQUEST';
export const BROWSING_HISTORY_ADD_SUCCESS = 'BROWSING_HISTORY_ADD_SUCCESS';
export const BROWSING_HISTORY_ADD_FAIL = 'BROWSING_HISTORY_ADD_FAIL';
export const BROWSING_HISTORY_ADD_RESET = 'BROWSING_HISTORY_ADD_RESET';
