export const BROWSING_HISTORY_ADD_REQUEST = 'BROWSING_HISTORY_ADD_REQUEST';
export const BROWSING_HISTORY_ADD_SUCCESS = 'BROWSING_HISTORY_ADD_SUCCESS';
export const BROWSING_HISTORY_ADD_FAIL = 'BROWSING_HISTORY_ADD_FAIL';
export const BROWSING_HISTORY_ADD_RESET = 'BROWSING_HISTORY_ADD_RESET';


export const BROWSING_HISTORY_LIST_REQUEST = 'BROWSING_HISTORY_LIST_REQUEST';
export const BROWSING_HISTORY_LIST_SUCCESS = 'BROWSING_HISTORY_LIST_SUCCESS';
export const BROWSING_HISTORY_LIST_FAIL = 'BROWSING_HISTORY_LIST_FAIL';
export const BROWSING_HISTORY_LIST_RESET = 'BROWSING_HISTORY_LIST_RESET';

export const BROWSING_HISTORY_DELETE_REQUEST = 'BROWSING_HISTORY_DELETE_REQUEST';
export const BROWSING_HISTORY_DELETE_SUCCESS = 'BROWSING_HISTORY_DELETE_SUCCESS';
export const BROWSING_HISTORY_DELETE_FAIL = 'BROWSING_HISTORY_DELETE_FAIL';
export const BROWSING_HISTORY_DELETE_RESET = 'BROWSING_HISTORY_DELETE_RESET';