export default {
  'All Categories': 'All Categories',
  'Arts, Crafts & Sewing': 'Arts, Crafts & Sewing',
  'Automotive & Motorcycle': 'Automotive & Motorcycle',
  Baby: 'Baby',
  'Baby Clothing & Accessories': 'Baby Clothing & Accessories',
  Beauty: 'Beauty',
  Books: 'Books',
  'Boys’ Fashion': 'Boys’ Fashion',
  'Camera & Photo': 'Camera & Photo',
  'Cell Phones & Accessories': 'Cell Phones & Accessories',
  'Computers & Accessories': 'Computers & Accessories',
  'Costumes & Accessories': 'Costumes & Accessories',
  Electronics: 'Electronics',
  'Everything Else': 'Everything Else',
  Fashion: 'Fashion',
  Furniture: 'Furniture',
  'Girls’ Fashion': 'Girls’ Fashion',
  Grocery: 'Grocery',
  Headphones: 'Headphones',
  'Health & Personal Care': 'Health & Personal Care',
  Home: 'Home',
  'Home Audio': 'Home Audio',
  'Home Improvement': 'Home Improvement',
  'Industrial & Scientific': 'Industrial & Scientific',
  Kindle: 'Kindle',
  'Kindle eBooks': 'Kindle eBooks',
  Kitchen: 'Kitchen',
  'Luggage Travel Gear': 'Luggage Travel Gear',
  Magazines: 'Magazines',
  'Major Appliances': 'Major Appliances',
  "Men's Shoes": "Men's Shoes",
  "Men's Watches": "Men's Watches",
  'Men’s Clothing': 'Men’s Clothing',
  'Men’s Fashion': 'Men’s Fashion',
  'Movies & TV': 'Movies & TV',
  Music: 'Music',
  'Musical Instruments': 'Musical Instruments',
  'Office Electronics & Supplies': 'Office Electronics & Supplies',
  'Patio, Lawn & Garden': 'Patio, Lawn & Garden',
  'Pet Supplies': 'Pet Supplies',
  'Power & Hand Tools': 'Power & Hand Tools',
  Software: 'Software',
  'Sports & Outdoors': 'Sports & Outdoors',
  'Television & Video': 'Television & Video',
  'Toys & Games': 'Toys & Games',
  'Video Games': 'Video Games',
  "Women's Shoes": "Women's Shoes",
  "Women's Watches": "Women's Watches",
  'Women’s Clothing': 'Women’s Clothing',
  'Women’s Fashion': 'Women’s Fashion',
  'Women’s Jewelry': 'Women’s Jewelry'
};
