const productSpecificationsEnum: { [key: string]: string } = {
  productId: 'Product Id',
  title: 'Title',
  image: 'Image',
  description: 'Description',
  brand: 'Brand',
  productCategory: 'Product Category',
  price: 'Price',
  stockCount: 'Stock Count',
  isDeleted: 'Is Deleted',
  modelNumber: 'Model Number',
  sku: 'SKU',
  releaseYear: 'Release Year',
  color: 'Color',
  weight: 'Weight',
  dimensions: 'Dimensions (HxWxD)',
  screenSize: 'Screen Size (inch)',
  screenResolution: 'Screen Resolution',
  displayType: 'Display',
  touchScreen: 'Touch Screen',
  processorBrand: 'Processor Brand',
  processorModel: 'Processor Model',
  processorModelNumber: 'Processor',
  storageType: 'Storage Type',
  storageCapacity: 'Storage Capacity',
  systemMemory: 'System Memory',
  graphicsType: 'Graphics Type',
  graphicsBrand: 'Graphics Brand',
  graphicsModel: 'Graphics Model',
  operatingSystem: 'Operating System',
  voiceAssistant: 'Voice Assistant',
  batteryType: 'Battery Type',
  backlitKeyboard: 'Backlit Keyboard',
  reviewCount: 'Review Count',
  rating: 'Ratings'
};

export default productSpecificationsEnum;
