export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

export const PRODUCT_RESTORE_REQUEST = 'PRODUCT_RESTORE_REQUEST';
export const PRODUCT_RESTORE_SUCCESS = 'PRODUCT_RESTORE_SUCCESS';
export const PRODUCT_RESTORE_FAIL = 'PRODUCT_RESTORE_FAIL';

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';

export const PRODUCT_FEATURES_LIST_REQUEST = 'PRODUCT_FEATURES_LIST_REQUEST';
export const PRODUCT_FEATURES_LIST_SUCCESS = 'PRODUCT_FEATURES_LIST_SUCCESS';
export const PRODUCT_FEATURES_LIST_FAIL = 'PRODUCT_FEATURES_LIST_FAIL';

export const PRODUCT_FEATURE_CREATE_REQUEST = 'PRODUCT_FEATURE_CREATE_REQUEST';
export const PRODUCT_FEATURE_CREATE_SUCCESS = 'PRODUCT_FEATURE_CREATE_SUCCESS';
export const PRODUCT_FEATURE_CREATE_FAIL = 'PRODUCT_FEATURE_CREATE_FAIL';
export const PRODUCT_FEATURE_CREATE_RESET = 'PRODUCT_FEATURE_CREATE_RESET';

export const PRODUCT_FEATURE_UPDATE_REQUEST = 'PRODUCT_FEATURE_UPDATE_REQUEST';
export const PRODUCT_FEATURE_UPDATE_SUCCESS = 'PRODUCT_FEATURE_UPDATE_SUCCESS';
export const PRODUCT_FEATURE_UPDATE_FAIL = 'PRODUCT_FEATURE_UPDATE_FAIL';
export const PRODUCT_FEATURE_UPDATE_RESET = 'PRODUCT_FEATURE_UPDATE_RESET';

export const PRODUCT_FEATURE_DELETE_REQUEST = 'PRODUCT_FEATURE_DELETE_REQUEST';
export const PRODUCT_FEATURE_DELETE_SUCCESS = 'PRODUCT_FEATURE_DELETE_SUCCESS';
export const PRODUCT_FEATURE_DELETE_FAIL = 'PRODUCT_FEATURE_DELETE_FAIL';

export const PRODUCT_SPECIFICATION_CREATE_REQUEST = 'PRODUCT_SPECIFICATION_CREATE_REQUEST';
export const PRODUCT_SPECIFICATION_CREATE_SUCCESS = 'PRODUCT_SPECIFICATION_CREATE_SUCCESS';
export const PRODUCT_SPECIFICATION_CREATE_FAIL = 'PRODUCT_SPECIFICATION_CREATE_FAIL';
export const PRODUCT_SPECIFICATION_CREATE_RESET = 'PRODUCT_SPECIFICATION_CREATE_RESET';

export const PRODUCT_SPECIFICATION_UPDATE_REQUEST = 'PRODUCT_SPECIFICATION_UPDATE_REQUEST';
export const PRODUCT_SPECIFICATION_UPDATE_SUCCESS = 'PRODUCT_SPECIFICATION_UPDATE_SUCCESS';
export const PRODUCT_SPECIFICATION_UPDATE_FAIL = 'PRODUCT_SPECIFICATION_UPDATE_FAIL';
export const PRODUCT_SPECIFICATION_UPDATE_RESET = 'PRODUCT_SPECIFICATION_UPDATE_RESET';

export const PRODUCT_SPECIFICATION_DELETE_REQUEST = 'PRODUCT_SPECIFICATION_DELETE_REQUEST';
export const PRODUCT_SPECIFICATION_DELETE_SUCCESS = 'PRODUCT_SPECIFICATION_DELETE_SUCCESS';
export const PRODUCT_SPECIFICATION_DELETE_FAIL = 'PRODUCT_SPECIFICATION_DELETE_FAIL';

export const PRODUCT_IMAGE_UPLOAD_REQUEST = 'PRODUCT_IMAGE_UPLOAD_REQUEST';
export const PRODUCT_IMAGE_UPLOAD_SUCCESS = 'PRODUCT_IMAGE_UPLOAD_SUCCESS';
export const PRODUCT_IMAGE_UPLOAD_FAIL = 'PRODUCT_IMAGE_UPLOAD_FAIL';

export const PRODUCT_IMAGES_LIST_REQUEST = 'PRODUCT_IMAGES_LIST_REQUEST';
export const PRODUCT_IMAGES_LIST_SUCCESS = 'PRODUCT_IMAGES_LIST_SUCCESS';
export const PRODUCT_IMAGES_LIST_FAIL = 'PRODUCT_IMAGES_LIST_FAIL';

export const PRODUCT_IMAGE_DELETE_REQUEST = 'PRODUCT_IMAGE_DELETE_REQUEST';
export const PRODUCT_IMAGE_DELETE_SUCCESS = 'PRODUCT_IMAGE_DELETE_SUCCESS';
export const PRODUCT_IMAGE_DELETE_FAIL = 'PRODUCT_IMAGE_DELETE_FAIL';

export const PRODUCT_IMAGE_SET_MAIN_REQUEST = 'PRODUCT_IMAGE_SET_MAIN_REQUEST';
export const PRODUCT_IMAGE_SET_MAIN_SUCCESS = 'PRODUCT_IMAGE_SET_MAIN_SUCCESS';
export const PRODUCT_IMAGE_SET_MAIN_FAIL = 'PRODUCT_IMAGE_SET_MAIN_FAIL';