export const productsDatabase = [
  {
    productId: 32,
    title:
      'ASUS - 11.6" Chromebook - Intel Celeron - 4GB Memory - 32GB eMMC Flash Memory - Gray - Grey',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6449/6449513_sd.jpg;maxHeight=200;maxWidth=300',
    description:
      'ASUS CX22NA Chromebook: Stay productive and entertained with this ASUS 11.6-inch Chromebook notebook. The 4GB memory ensure fast startups, while the Intel Celeron processor and 32GB eMMC Flash Memory offer smooth performance. This ASUS 11.6-inch Chromebook notebook has an LED-backlit HD display that provides an engaging viewing experience and is easily visible in dark environments.\n',
    brand: 'ASUS',
    productCategory: 'Electornics',
    weight: 219,
    stockCount: 89,
    isDeleted: 0,
    modelNumber: 'CX22NA-211.BB01',
    sku: '6449513',
    releaseYear: 2021,
    dateCreated: '2021-11-15T08:00:00.000Z',
    color: 'Space Gray',
    colorFamily: 'Gray',
    weight: 2.6,
    dimensions: '0.68  x 7.83  x 11.26 ',
    screenSize: 11.6,
    screenResolution: '1600 x 768',
    displayType: 'LED',
    touchScreen: 0,
    processorBrand: 'Intel',
    processorModel: 'Intel Celeron',
    processorModelNumber: 'N3350',
    storageType: 'eMMC',
    storageCapacity: 32,
    systemMemory: 4,
    graphicsType: 'Integrated',
    graphicsBrand: 'Intel',
    graphicsModel: 'Intel UHD Graphics',
    operatingSystem: 'Chrome OS',
    voiceAssistant: 'No',
    batteryType: 'Lithium-ion polymer',
    backlitKeyboard: 0,
    reviewCount: 20,
    rating: 4,
    starOne: 1,
    starTwo: 0,
    starThree: 0,
    starFour: 16,
    starFive: 3
  },
  {
    productId: 38,
    title: 'HP - 14" Laptop - Intel Celeron - 4GB Memory - 64GB eMMC - Indigo Blue',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6437/6437580_sd.jpg;maxHeight=300;maxWidth=450',
    description:
      'Designed to keep you productive and entertained from anywhere, the HP 14-inch diagonal laptop combines long lasting battery life with a thin and portable, microedge bezel design.\n',
    brand: 'HP',
    productCategory: 'Electornics',
    price: 249.99,
    stockCount: 33,
    isDeleted: 0,
    modelNumber: '14-dq0005dx',
    sku: '6437580',
    releaseYear: 2020,
    dateCreated: '2021-11-21T08:00:00.000Z',
    color: 'Indigo Blue',
    colorFamily: 'Blue',
    weight: 3.2,
    dimensions: '0.7  x 12.7  x 8.8 ',
    screenSize: 14,
    screenResolution: '1366 x 768',
    displayType: 'LED',
    touchScreen: 0,
    processorBrand: 'Intel',
    processorModel: 'Intel Celeron',
    processorModelNumber: 'Intel® Celeron® N4020',
    storageType: 'eMMC',
    storageCapacity: 64,
    systemMemory: 4,
    graphicsType: 'Integrated',
    graphicsBrand: 'Intel',
    graphicsModel: 'Intel UHD Graphics 600',
    operatingSystem: 'Windows 11 Home',
    voiceAssistant: 'No',
    batteryType: 'Lithium-ion polymer',
    backlitKeyboard: 0,
    reviewCount: 20,
    rating: 4.5,
    starOne: 1,
    starTwo: 1,
    starThree: 0,
    starFour: 3,
    starFive: 15
  },
  {
    productId: 11,
    title:
      'Lenovo Chromebook 3 14" Laptop - Mediatek MT8183 - 4GB Memory - 64GB eMMC - Arctic Grey',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6447/6447138_sd.jpg;maxHeight=200;maxWidth=300',
    description:
      'Fast, flexible, and fun, the Chromebook 3-14" brings everyone’s favorite Chromebook features, running on the lightning-fast Chrome OS that boots up in seconds, updates automatically, and is protected by built-in virus protection. Powered by a MediaTek processor and up to 10 hours of battery life, it’ll seamlessly run all of your favorite apps at the same time.\n',
    brand: 'Lenovo',
    productCategory: 'Electornics',
    price: 289,
    stockCount: 5,
    isDeleted: 0,
    modelNumber: '82KN0000US',
    sku: '6447138',
    releaseYear: 2021,
    dateCreated: '2021-11-12T08:00:00.000Z',
    color: 'Arctic Grey',
    colorFamily: 'Gray',
    weight: 3.08,
    dimensions: '0.74  x 9.23  x 12.95 ',
    screenSize: 14,
    screenResolution: '1920 x 1080 ',
    displayType: 'IPS',
    touchScreen: 0,
    processorBrand: 'MediaTek',
    processorModel: 'MediaTek',
    processorModelNumber: 'MT8183',
    storageType: 'eMMC',
    storageCapacity: 64,
    systemMemory: 4,
    graphicsType: 'Integrated',
    graphicsBrand: 'None',
    graphicsModel: 'Other',
    operatingSystem: 'Chrome OS',
    voiceAssistant: 'No',
    batteryType: 'Lithium-ion polymer',
    backlitKeyboard: 0,
    reviewCount: 20,
    rating: 4.45,
    starOne: 0,
    starTwo: 0,
    starThree: 1,
    starFour: 9,
    starFive: 10
  },
  {
    productId: 9,
    title:
      'Lenovo Chromebook 3 14" Touch Laptop - Mediatek MT8183 - 4GB Memory - 64GB eMMC - Arctic Grey',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6447/6447140_sd.jpg;maxHeight=200;maxWidth=300',
    description:
      'Fast, flexible, and fun, the Chromebook 3-14" brings everyone’s favorite Chromebook features, running on the lightning-fast Chrome OS that boots up in seconds, updates automatically, and is protected by built-in virus protection. Powered by a MediaTek processor and up to 10 hours of battery life, it’ll seamlessly run all of your favorite apps at the same time.\n',
    brand: 'Lenovo',
    productCategory: 'Electornics',
    price: 319,
    stockCount: 5,
    isDeleted: 0,
    modelNumber: '82KN0001US',
    sku: '6447140',
    releaseYear: 2021,
    dateCreated: '2021-11-10T08:00:00.000Z',
    color: 'Arctic Grey',
    colorFamily: 'Gray',
    weight: 3.08,
    dimensions: '0.74  x 9.23  x 12.95 ',
    screenSize: 14,
    screenResolution: '1920 x 1080 ',
    displayType: 'LED',
    touchScreen: 1,
    processorBrand: 'MediaTek',
    processorModel: 'MediaTek',
    processorModelNumber: 'Mediatek MT8183',
    storageType: 'eMMC',
    storageCapacity: 64,
    systemMemory: 4,
    graphicsType: 'Integrated',
    graphicsBrand: 'NVIDIA',
    graphicsModel: 'Other',
    operatingSystem: 'Chrome OS',
    voiceAssistant: 'No',
    batteryType: 'Lithium-ion polymer',
    backlitKeyboard: 0,
    reviewCount: 40,
    rating: 4.7,
    starOne: 0,
    starTwo: 0,
    starThree: 1,
    starFour: 10,
    starFive: 29
  },
  {
    productId: 2,
    title:
      'Lenovo - Ideapad 3 15 15.6" Laptop - AMD Ryzen 3 - 8GB Memory - 128GB SSD - Platinum Grey',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6449/6449503_sd.jpg;maxHeight=200;maxWidth=300',
    description:
      "Engineered for long-lasting performance, the Lenovo™ IdeaPad™ 3 delivers powerful performance with the latest AMD Mobile Processors with Radeon™ Graphics, in a laptop that's perfect for your everyday tasks, with features that you can depend on.\n",
    brand: 'Lenovo',
    productCategory: 'Electornics',
    price: 399.99,
    stockCount: 435,
    isDeleted: 0,
    modelNumber: '81W1018XUS',
    sku: '6449503',
    releaseYear: 2020,
    dateCreated: '2021-11-02T07:00:00.000Z',
    color: 'Platinum Grey',
    colorFamily: 'Platinum',
    weight: 5.73,
    dimensions: '1.02  x 9.98  x 14.26 ',
    screenSize: 15.6,
    screenResolution: '1920 x 1080 ',
    displayType: 'IPS',
    touchScreen: 0,
    processorBrand: 'AMD',
    processorModel: 'AMD Ryzen 3',
    processorModelNumber: 'AMD Ryzen 3 3250U',
    storageType: 'SSD',
    storageCapacity: 128,
    systemMemory: 8,
    graphicsType: 'Integrated',
    graphicsBrand: 'AMD Radeon',
    graphicsModel: 'AMD Radeon',
    operatingSystem: 'Windows 11 Home',
    voiceAssistant: 'No',
    batteryType: 'Lithium-ion polymer',
    backlitKeyboard: 0,
    reviewCount: 20,
    rating: 4.45,
    starOne: 0,
    starTwo: 0,
    starThree: 0,
    starFour: 11,
    starFive: 9
  },
  {
    productId: 35,
    title:
      'HP - 14" 2-In-1 Touchscreen Chromebook - Intel Celeron - 4GB Memory - 32GB eMMC - Natural Silver',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6455/6455902_sd.jpg;maxHeight=300;maxWidth=450',
    description:
      'Powered up: The Chromebook x360 is powered by an Intel® processor and packed full of the features you have to have, like a long battery life, and a full-size keyboard. An entertainment experience that adapts to you: With the versatility of a 360° hinge, the beauty of a micro-edge, HD touch display and Audio by B&O, your entertainment experience looks as good as it sounds. Apps for everything: Redefine how you work and play with the seamless integration of your favorite Chrome browser, always secure and up to date, and access to a huge selection of apps in the Google Play Store.\n',
    brand: 'HP',
    productCategory: 'Electornics',
    price: 409,
    stockCount: 26,
    isDeleted: 0,
    modelNumber: '14b-cb0013dx',
    sku: '6455902',
    releaseYear: 2021,
    dateCreated: '2021-11-18T08:00:00.000Z',
    color: 'Natural Silver',
    colorFamily: 'Silver',
    weight: 3.57,
    dimensions: '0.73  x 12.85  x 8.65 ',
    screenSize: 14,
    screenResolution: '1920 x 1080 ',
    displayType: 'LED',
    touchScreen: 1,
    processorBrand: 'Intel',
    processorModel: 'Intel Celeron',
    processorModelNumber: 'Intel® Celeron® N4500',
    storageType: 'eMMC',
    storageCapacity: 32,
    systemMemory: 4,
    graphicsType: 'Integrated',
    graphicsBrand: 'Intel',
    graphicsModel: 'Intel UHD Graphics',
    operatingSystem: 'Chrome OS',
    voiceAssistant: 'Google Assistant',
    batteryType: 'Lithium-ion',
    backlitKeyboard: 0,
    reviewCount: 20,
    rating: 4.7,
    starOne: 0,
    starTwo: 0,
    starThree: 1,
    starFour: 4,
    starFive: 15
  },
  {
    productId: 3,
    title:
      'Dell - Inspiron 15.6" FHD Touch-Screen Laptop -AMD Ryzen 5 - 8GB Memory - 256GB SSD - Black',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6447/6447112_sd.jpg;maxHeight=200;maxWidth=300',
    description:
      "Power through the day with the new Inspiron 3505 15.6'' laptop. Featuring Windows 11 in S mode, an AMD Ryzen Processor, Vega 8 graphics and 8 GB memory, the Inspiron 15 3505 is designed to keep you productive -- at school, home, or wherever life takes you. With ExpressCharging Mode, get your battery from 0% up to 80% within an hour, so that you're not tied down to an outlet while out and about. This model can be customized with Dell Mobile Connect for integration with both iOS and Android mobile devices. No matter your lifestyle, the Inspiron laptop is perfect for daily use, remote learning, kids, streaming, and more.\n",
    brand: 'Dell',
    productCategory: 'Electornics',
    price: 419.99,
    stockCount: 34,
    isDeleted: 0,
    modelNumber: 'i3505-A542BLK-PUS',
    sku: '6447112',
    releaseYear: 2021,
    dateCreated: '2021-11-03T07:00:00.000Z',
    color: 'Black',
    colorFamily: 'Black',
    weight: 4.04,
    dimensions: '0.71  x 14.33  x 9.8 ',
    screenSize: 15.6,
    screenResolution: '1920 x 1080 ',
    displayType: 'LED',
    touchScreen: 1,
    processorBrand: 'AMD',
    processorModel: 'AMD Ryzen 5',
    processorModelNumber: 'AMD Ryzen™ 5 3450U',
    storageType: 'SSD',
    storageCapacity: 256,
    systemMemory: 8,
    graphicsType: 'Integrated',
    graphicsBrand: 'AMD Radeon',
    graphicsModel: 'AMD Radeon Vega 8',
    operatingSystem: 'Windows 11 Home',
    voiceAssistant: 'No',
    batteryType: 'Alkaline',
    backlitKeyboard: 0,
    reviewCount: 20,
    rating: 4.4,
    starOne: 1,
    starTwo: 0,
    starThree: 1,
    starFour: 6,
    starFive: 12
  },
  {
    productId: 10,
    title: 'HP - 15.6" Laptop Intel Core i3 - 8GB Memory - 256GB SSD - Natural Silver',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6461/6461985_sd.jpg;maxHeight=200;maxWidth=300',
    description:
      'See more. Take it anywhere. With its 6.5 mm micro-edge bezel display, slim and light design, plus 81% screen to body ratio – this PC lets you see more and do more, no matter where the day takes you. Reliable performance for every day: Powerful enough for your busiest days – this PC features an Intel® processor and integrated graphics. Powered up and productive. All day long. Designed for all-day productivity with extended battery life and fingerprint reader technology.\n',
    brand: 'HP',
    productCategory: 'Electornics',
    price: 499.99,
    stockCount: 344,
    isDeleted: 0,
    modelNumber: '15-dw3033dx',
    sku: '6461985',
    releaseYear: 2021,
    dateCreated: '2021-11-11T08:00:00.000Z',
    color: 'Natural Silver',
    colorFamily: 'Silver',
    weight: 3.86,
    dimensions: '0.78  x 14.1  x 9.53 ',
    screenSize: 15.6,
    screenResolution: '1920 x 1080 ',
    displayType: 'IPS',
    touchScreen: 0,
    processorBrand: 'Intel',
    processorModel: 'Intel 11th Gen Core i3',
    processorModelNumber: '11th Generation Intel® Core™ i3-1115G4',
    storageType: 'SSD',
    storageCapacity: 256,
    systemMemory: 8,
    graphicsType: 'Integrated',
    graphicsBrand: 'Intel',
    graphicsModel: 'Intel UHD Graphics',
    operatingSystem: 'Windows 11 Home',
    voiceAssistant: 'No',
    batteryType: 'Lithium-ion',
    backlitKeyboard: 0,
    reviewCount: null,
    rating: null,
    starOne: null,
    starTwo: null,
    starThree: null,
    starFour: null,
    starFive: null
  },
  {
    productId: 8,
    title:
      'Dell - Inspiron 15.6" FHD Touch-Screen Laptop -Intel Core i5 - 8GB Memory - 256GB SSD - Black',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6447/6447114_sd.jpg;maxHeight=200;maxWidth=300',
    description:
      'Get your hands on a versatile 15 inch laptop packed with features for an enjoyable multimedia experience. All at an affordable price.\n',
    brand: 'Dell',
    productCategory: 'Electornics',
    price: 549.99,
    stockCount: 4,
    isDeleted: 0,
    modelNumber: 'i3501-5573BLK-PUS',
    sku: '6447114',
    releaseYear: 2021,
    dateCreated: '2021-11-09T08:00:00.000Z',
    color: 'Black',
    colorFamily: 'Black',
    weight: 3.93,
    dimensions: '0.71  x 14.33  x 9.8 ',
    screenSize: 15.6,
    screenResolution: '1920 x 1080 ',
    displayType: 'LED',
    touchScreen: 1,
    processorBrand: 'Intel',
    processorModel: 'Intel 10th Gen Core i5',
    processorModelNumber: '10th Generation Intel® Core™ i5-1035G1',
    storageType: 'SSD',
    storageCapacity: 256,
    systemMemory: 8,
    graphicsType: 'Integrated',
    graphicsBrand: 'Intel',
    graphicsModel: 'Intel UHD Graphics',
    operatingSystem: 'Windows 11 Home',
    voiceAssistant: 'No',
    batteryType: 'Alkaline',
    backlitKeyboard: 0,
    reviewCount: 20,
    rating: 4.7,
    starOne: 1,
    starTwo: 0,
    starThree: 0,
    starFour: 2,
    starFive: 17
  },
  {
    productId: 5,
    title: 'HP - 17.3" Laptop - Intel Core i5 - 8GB Memory - 256GB SSD - Natural Silver',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6461/6461988_sd.jpg;maxHeight=200;maxWidth=300',
    description:
      'Responsive and reliable performance: Surf, stream, and do so much more with a powerful Intel® Core™ processor. Plus, extensive quality testing ensures that your laptop keeps going … and going. Sleek. Stylish. Portable. With a sleek and stylish design, this eye-catching laptop looks as good as it performs and is easy to take anywhere. Stay Connected and Entertained: Stay connected and entertained with a longlasting battery with HP Fast Charge. Store more of what you love with ample storage options.\n',
    brand: 'HP',
    productCategory: 'Electornics',
    price: 579.99,
    stockCount: 32,
    isDeleted: 0,
    modelNumber: '17-by4633dx',
    sku: '6461988',
    releaseYear: 2021,
    dateCreated: '2021-11-06T07:00:00.000Z',
    color: 'Natural Silver',
    colorFamily: 'Silver',
    weight: 5.25,
    dimensions: '0.96  x 16.33  x 10.72 ',
    screenSize: 17.3,
    screenResolution: '1920 x 1080 ',
    displayType: 'IPS',
    touchScreen: 0,
    processorBrand: 'Intel',
    processorModel: 'Intel 11th Gen Core i5',
    processorModelNumber: '11th Generation Intel® Core™ i5-1135G7',
    storageType: 'SSD',
    storageCapacity: 256,
    systemMemory: 8,
    graphicsType: 'Integrated',
    graphicsBrand: 'Intel',
    graphicsModel: 'Intel Iris Xe Graphics',
    operatingSystem: 'Windows 11 Home',
    voiceAssistant: 'No',
    batteryType: 'Lithium-ion',
    backlitKeyboard: 0,
    reviewCount: 20,
    rating: 4.85,
    starOne: 0,
    starTwo: 0,
    starThree: 0,
    starFour: 3,
    starFive: 17
  },
  {
    productId: 39,
    title:
      'Microsoft - Surface Pro 7 - 12.3" Touch Screen - Intel Core i3 - 4GB Memory - 128GB SSD with Black Type Cover - Platinum',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6374/6374985_sd.jpg;maxHeight=300;maxWidth=450',
    description:
      'At your desk, on the couch, or out in the yard, Surface Pro 7 adapts to the way you work with laptop-to-tablet versatility. And now, it delivers more power than ever, with a laptop-class Intel® Core™ processor, all-day battery¹, Instant On, and improved graphics — plus more multitasking connections, including both USB-C® and USB-A ports. ',
    brand: 'Microsoft',
    productCategory: 'Electornics',
    price: 599,
    stockCount: 63,
    isDeleted: 0,
    modelNumber: 'QWT-00001',
    sku: '6374985',
    releaseYear: 2019,
    dateCreated: '2021-11-22T08:00:00.000Z',
    color: 'Platinum',
    colorFamily: 'Platinum',
    weight: 2.38,
    dimensions: '11.5  x 7.9  x 0.33 ',
    screenSize: 12.3,
    screenResolution: '2736 x 1824',
    displayType: 'PixelSense',
    touchScreen: 0,
    processorBrand: 'Intel',
    processorModel: 'Intel 10th Gen Core i3',
    processorModelNumber: 'Intel Core i3-1005G1',
    storageType: 'SSD',
    storageCapacity: 128,
    systemMemory: 4,
    graphicsType: 'Integrated',
    graphicsBrand: 'Intel',
    graphicsModel: 'Other',
    operatingSystem: 'Windows 10',
    voiceAssistant: 'No',
    batteryType: 'Lithium-ion',
    backlitKeyboard: 0,
    reviewCount: 20,
    rating: 4.15,
    starOne: 3,
    starTwo: 1,
    starThree: 0,
    starFour: 2,
    starFive: 14
  },
  {
    productId: 36,
    title:
      'Lenovo Ideapad 3 15.6" FHD Touch Screen Laptop - Intel Core i5 11th Gen - 12GB Memory - 256GB SSD - Arctic Grey',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6461/6461977_sd.jpg;maxHeight=300;maxWidth=450',
    description:
      "Engineered for long-lasting performance, the Lenovo™ IdeaPad™ 3 delivers powerful performance with the latest Intel 11th Generation Processors with Intel™ Iris Xe Graphics, in a laptop that's perfect for your everyday tasks, with features that you can depend on.\n",
    brand: 'Lenovo',
    productCategory: 'Electornics',
    price: 619.99,
    stockCount: 77,
    isDeleted: 0,
    modelNumber: '82H8018SUS/82H801DQUS',
    sku: '6461977',
    releaseYear: 2021,
    dateCreated: '2021-11-19T08:00:00.000Z',
    color: 'Arctic Grey',
    colorFamily: 'Gray',
    weight: 3.74,
    dimensions: '0.78  x 9.98  x 14.26 ',
    screenSize: 15.6,
    screenResolution: '1920 x 1080 ',
    displayType: 'LCD',
    touchScreen: 1,
    processorBrand: 'Intel',
    processorModel: 'Intel 11th Gen Core i5',
    processorModelNumber: 'Intel Core i5-1135G7',
    storageType: 'SSD',
    storageCapacity: 256,
    systemMemory: 12,
    graphicsType: 'Integrated',
    graphicsBrand: 'Intel',
    graphicsModel: 'Intel Iris Xe Graphics',
    operatingSystem: 'Windows 11 Home',
    voiceAssistant: 'No',
    batteryType: 'Lithium-ion polymer',
    backlitKeyboard: 1,
    reviewCount: 20,
    rating: 4.75,
    starOne: 0,
    starTwo: 0,
    starThree: 1,
    starFour: 3,
    starFive: 16
  },
  {
    productId: 12,
    title:
      'ASUS - TUF Gaming 17.3" Laptop - Intel Core i5 - 8GB Memory - NVIDIA GeForce RTX3050 Ti - 512GB SSD - Eclipse Grey',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6464/6464212_sd.jpg;maxHeight=200;maxWidth=300',
    description:
      'The latest Intel 11th Core i5 processor with GeForce® RTX3050 Ti graphics also equipped with a large 17.3" FHD 144hz display. Personalize your laptop with RGB keyboard.\n',
    brand: 'ASUS',
    productCategory: 'Electornics',
    price: 779.99,
    stockCount: 54,
    isDeleted: 0,
    modelNumber: 'FX706HE-211.TM17',
    sku: '6464212',
    releaseYear: 2021,
    dateCreated: '2021-11-13T08:00:00.000Z',
    color: 'Eclipse Grey',
    colorFamily: 'Gray',
    weight: 3.08,
    dimensions: '0.74  x 10.59  x 15.71 ',
    screenSize: 17.3,
    screenResolution: '1920 x 1080 ',
    displayType: 'LED',
    touchScreen: 0,
    processorBrand: 'Intel',
    processorModel: 'Intel 11th Gen Core i5',
    processorModelNumber: 'i5-11260H',
    storageType: 'SSD',
    storageCapacity: 512,
    systemMemory: 8,
    graphicsType: 'Dedicated',
    graphicsBrand: 'NVIDIA',
    graphicsModel: 'NVIDIA GeForce RTX 3050 Ti',
    operatingSystem: 'Windows 10',
    voiceAssistant: 'No',
    batteryType: 'Lithium-ion polymer',
    backlitKeyboard: 1,
    reviewCount: 20,
    rating: 4.55,
    starOne: 0,
    starTwo: 0,
    starThree: 0,
    starFour: 9,
    starFive: 11
  },
  {
    productId: 1,
    title:
      'HP - ENVY x360 2-in-1 15.6" Touch-Screen Laptop - AMD Ryzen 5 - 8GB Memory - 256GB SSD - Nightfall Black',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6453/6453188_sd.jpg;maxHeight=200;maxWidth=300',
    description:
      'Dominate the battlefield with Acer’s new Nitro 5 gaming laptop, including everything you need to take control of the action. The powerful Nitro 5 laptop was developed to deliver an iconic gaming experience courtesy of the many awesome features inside, including its 11th Gen Intel® Core™ processor and high-performance NVIDIA® GeForce RTX 3050 Ti laptop graphics—that’s powered by the 2nd gen NVIDIA Ampere™ architecture! Next, toss in its 15.6” FHD IPS 144Hz refresh rate display, awesome mobility, advanced cooling and stellar audio capabilities, and all of the other gaming-rich features, and you quickly see why the Nitro 5 delivers a knockout blow to the competition!\n',
    brand: 'HP',
    productCategory: 'Electornics',
    price: 819.99,
    stockCount: 0,
    isDeleted: 0,
    modelNumber: '15m-eu0013dx',
    sku: '6453188',
    releaseYear: 2021,
    dateCreated: '2021-11-01T07:00:00.000Z',
    color: 'Nightfall Black',
    colorFamily: 'Black',
    weight: 4.1,
    dimensions: '0.72  x 14.13  x 8.98 ',
    screenSize: 15.6,
    screenResolution: '1920 x 1080 ',
    displayType: 'IPS',
    touchScreen: 1,
    processorBrand: 'AMD',
    processorModel: 'AMD Ryzen 5',
    processorModelNumber: 'AMD Ryzen 5 5500U',
    storageType: 'SSD',
    storageCapacity: 256,
    systemMemory: 8,
    graphicsType: 'Integrated',
    graphicsBrand: 'AMD Radeon',
    graphicsModel: 'AMD Radeon',
    operatingSystem: 'Windows 11 Home',
    voiceAssistant: 'Amazon Alexa',
    batteryType: 'Lithium-ion polymer',
    backlitKeyboard: 1,
    reviewCount: 20,
    rating: 4.55,
    starOne: 1,
    starTwo: 0,
    starThree: 0,
    starFour: 5,
    starFive: 14
  },
  {
    productId: 4,
    title:
      'MacBook Air 13.3" Laptop - Apple M1 chip - 8GB Memory - 256GB SSD (Latest Model) - Space Gray',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5721/5721600_sd.jpg;maxHeight=200;maxWidth=300',
    description:
      'Apple’s thinnest and lightest notebook gets supercharged with the Apple M1 chip. Tackle your projects with the blazing-fast 8-core CPU. Take graphics-intensive apps and games to the next level with the 7-core GPU. And accelerate machine learning tasks with the 16-core Neural Engine. All with a silent, fanless design and the longest battery life ever — up to 18 hours.¹ MacBook Air. Still perfectly portable. Just a lot more powerful.\n',
    brand: 'Apple',
    productCategory: 'Electornics',
    price: 849.99,
    stockCount: 54,
    isDeleted: 0,
    modelNumber: 'MGN63LL/A',
    sku: '5721600',
    releaseYear: 2020,
    dateCreated: '2021-11-04T07:00:00.000Z',
    color: 'Space Gray',
    colorFamily: 'Gray',
    weight: 2.8,
    dimensions: '0.63  x 11.97  x 8.36 ',
    screenSize: 13.3,
    screenResolution: '2560 x 1600 ',
    displayType: 'LED',
    touchScreen: 0,
    processorBrand: 'Apple',
    processorModel: 'Apple M1',
    processorModelNumber: 'Apple M1',
    storageType: 'SSD',
    storageCapacity: 256,
    systemMemory: 8,
    graphicsType: 'Integrated',
    graphicsBrand: 'Apple',
    graphicsModel: 'Apple M1',
    operatingSystem: 'macOS Big Sur 11.0',
    voiceAssistant: 'Apple Siri',
    batteryType: 'Lithium-polymer',
    backlitKeyboard: 1,
    reviewCount: 20,
    rating: 4.85,
    starOne: 0,
    starTwo: 0,
    starThree: 0,
    starFour: 3,
    starFive: 17
  },
  {
    productId: 33,
    title:
      'MacBook Air 13.3" Laptop - Apple M1 chip - 8GB Memory - 256GB SSD (Latest Model) - Silver',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6418/6418597_sd.jpg;maxHeight=200;maxWidth=300',
    description:
      'Apple’s thinnest and lightest notebook gets supercharged with the Apple M1 chip. Tackle your projects with the blazing-fast 8-core CPU. Take graphics-intensive apps and games to the next level with the 7-core GPU. And accelerate machine learning tasks with the 16-core Neural Engine. All with a silent, fanless design and the longest battery life ever — up to 18 hours.¹ MacBook Air. Still perfectly portable. Just a lot more powerful. ',
    brand: 'Apple',
    productCategory: 'Electornics',
    price: 849.99,
    stockCount: 35,
    isDeleted: 0,
    modelNumber: 'MGN93LL/A',
    sku: '6418597',
    releaseYear: 2020,
    dateCreated: '2021-11-16T08:00:00.000Z',
    color: 'Silver',
    colorFamily: 'Silver',
    weight: 2.8,
    dimensions: '0.63  x 11.97  x 8.36 ',
    screenSize: 13.3,
    screenResolution: '2560 x 1600 ',
    displayType: 'LED',
    touchScreen: 0,
    processorBrand: 'Apple',
    processorModel: 'Apple M1',
    processorModelNumber: 'Apple M1',
    storageType: 'SSD',
    storageCapacity: 256,
    systemMemory: 8,
    graphicsType: 'Integrated',
    graphicsBrand: 'Apple',
    graphicsModel: 'Apple M1',
    operatingSystem: 'macOS Big Sur 11.0',
    voiceAssistant: 'Apple Siri',
    batteryType: 'Lithium-polymer',
    backlitKeyboard: 1,
    reviewCount: 20,
    rating: 4.85,
    starOne: 0,
    starTwo: 0,
    starThree: 0,
    starFour: 3,
    starFive: 17
  },
  {
    productId: 7,
    title:
      'Dell - Inspiron 2-in-1 - 14" Touch-Screen Laptop - Intel Core i5 - 8GB Memory - 512GB Solid State Drive - Silver',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6458/6458905_sd.jpg;maxHeight=200;maxWidth=300',
    description:
      'The Inspiron range of laptops and 2-in1s are thoughtfully designed so you can stay connected wherever you are, with long-lasting battery life, these chic, lightweight devices can seamlessly connect your PC and smartphone with Dell Mobile Connect’s wireless integration. Equipped with the latest processors, graphics, and thermal solutions; your PC runs quickly and smoothly as you connect with confidence. Optimized with technology that simplifies your life, Inspiron laptops and 2-in-1s offer a range of easy-to-use features all packaged in a minimalist and modern design. A newly designed and ergonomically positioned lift hinge increases comfort for a better typing experience when on chat, writing lengthy emails or connecting to your world. And that’s not all, your Inspiron, is now environmentally conscious – The Inspiron compliments not just your style but also your values.\n',
    brand: 'Dell',
    productCategory: 'Electornics',
    price: 879.99,
    stockCount: 54,
    isDeleted: 0,
    modelNumber: 'i5410-5181SLV-PUS/i5410-5149SLV-PUS',
    sku: '6458905',
    releaseYear: 2021,
    dateCreated: '2021-11-08T08:00:00.000Z',
    color: 'Silver',
    colorFamily: 'Silver',
    weight: 5.58,
    dimensions: '0.71  x 12.66  x 8.32 ',
    screenSize: 14,
    screenResolution: '1920 x 1080 ',
    displayType: 'LED',
    touchScreen: 1,
    processorBrand: 'Intel',
    processorModel: 'Intel 10th Gen Core i5',
    processorModelNumber: '11th Generation Intel® Core™ i5-1155G7',
    storageType: 'SSD',
    storageCapacity: 512,
    systemMemory: 8,
    graphicsType: 'Integrated',
    graphicsBrand: 'Intel',
    graphicsModel: 'Intel Iris Xe Graphics',
    operatingSystem: 'Windows 11 Home',
    voiceAssistant: 'No',
    batteryType: 'Lithium-ion',
    backlitKeyboard: 1,
    reviewCount: 20,
    rating: 4.75,
    starOne: 0,
    starTwo: 0,
    starThree: 0,
    starFour: 5,
    starFive: 15
  },
  {
    productId: 6,
    title:
      'Lenovo - Yoga 7i 2-in-1 14" Touch Screen Laptop - Intel Evo Platform Core i5 - 12GB Memory - 512GB Solid State Drive - Dark Moss',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6426/6426710_sd.jpg;maxHeight=200;maxWidth=300',
    description:
      'The Lenovo™ Yoga™ 7i 14" combines versatile portability and enhanced productivity, thanks to the boundary-breaking performance and responsiveness of 11th generation Intel® Core™ i5 processors and vibrant FHD clarity with Intel® Iris® X graphics. Go anywhere with a sleek 2-in-1 metal chassis featuring thoughtful details including a webcam privacy shutter.\n',
    brand: 'Lenovo',
    productCategory: 'Electornics',
    price: 949.99,
    stockCount: 5,
    isDeleted: 0,
    modelNumber: '82BH0006US/82BH00DQUS',
    sku: '6426710',
    releaseYear: 2021,
    dateCreated: '2021-11-07T07:00:00.000Z',
    color: 'Dark Moss',
    colorFamily: 'Green',
    weight: 3.08,
    dimensions: '0.7  x 12.61  x 8.45 ',
    screenSize: 14,
    screenResolution: '1920 x 1080 ',
    displayType: 'LED',
    touchScreen: 1,
    processorBrand: 'Intel',
    processorModel: 'Intel 11th Gen Core i5',
    processorModelNumber: '1135G7',
    storageType: 'SSD',
    storageCapacity: 512,
    systemMemory: 12,
    graphicsType: 'Integrated',
    graphicsBrand: 'Intel',
    graphicsModel: 'Intel Iris Xe Graphics',
    operatingSystem: 'Windows 11 Home',
    voiceAssistant: 'Amazon Alexa',
    batteryType: 'Lithium-polymer',
    backlitKeyboard: 1,
    reviewCount: 20,
    rating: 4.3,
    starOne: 3,
    starTwo: 0,
    starThree: 1,
    starFour: 0,
    starFive: 16
  },
  {
    productId: 13,
    title:
      'Acer - Nitro 5 – Gaming Laptop - 15.6" FHD 144Hz – Intel 11th Gen i7 - GeForce RTX 3050Ti - 16GB DDR4 - 512GB SSD – Windows 11',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6467/6467423_sd.jpg;maxHeight=200;maxWidth=300',
    description:
      'Dominate the battlefield with Acer’s new Nitro 5 gaming laptop, including everything you need to take control of the action. The powerful Nitro 5 laptop was developed to deliver an iconic gaming experience courtesy of the many awesome features inside, including its 11th Gen Intel® Core™ processor and high-performance NVIDIA® GeForce RTX 3050 Ti laptop graphics—that’s powered by the 2nd gen NVIDIA Ampere™ architecture! Next, toss in its 15.6” FHD IPS 144Hz refresh rate display, awesome mobility, advanced cooling and stellar audio capabilities, and all of the other gaming-rich features, and you quickly see why the Nitro 5 delivers a knockout blow to the competition!\n',
    brand: 'Acer',
    productCategory: 'Electornics',
    price: 1099.99,
    stockCount: 89,
    isDeleted: 0,
    modelNumber: 'AN515-57-74TT',
    sku: '6462658',
    releaseYear: 2020,
    dateCreated: '2021-11-14T08:00:00.000Z',
    color: 'Black',
    colorFamily: 'Black',
    weight: 5.73,
    dimensions: '1.02  x 9.98  x 14.3 ',
    screenSize: 15.6,
    screenResolution: '1920 x 1080 ',
    displayType: 'LED',
    touchScreen: 0,
    processorBrand: 'Intel',
    processorModel: 'Intel 11th Gen Core i7',
    processorModelNumber: 'i7-11800H',
    storageType: 'SSD',
    storageCapacity: 512,
    systemMemory: 16,
    graphicsType: 'Dedicated',
    graphicsBrand: 'NVIDIA',
    graphicsModel: 'NVIDIA GeForce RTX 3050 Ti',
    operatingSystem: 'Windows 11 Home',
    voiceAssistant: 'No',
    batteryType: 'Lithium-ion',
    backlitKeyboard: 1,
    reviewCount: 20,
    rating: 4.9,
    starOne: 0,
    starTwo: 0,
    starThree: 0,
    starFour: 2,
    starFive: 18
  },
  {
    productId: 34,
    title:
      'MacBook Air 13.3" Laptop - Apple M1 chip - 8GB Memory - 512GB SSD (Latest Model) - Space Gray',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6200/6200722_sd.jpg;maxHeight=200;maxWidth=300',
    description:
      'Apple’s thinnest and lightest notebook gets supercharged with the Apple M1 chip. Tackle your projects with the blazing-fast 8-core CPU. Take graphics-intensive apps and games to the next level with the 7-core GPU. And accelerate machine learning tasks with the 16-core Neural Engine. All with a silent, fanless design and the longest battery life ever — up to 18 hours.¹ MacBook Air. Still perfectly portable. Just a lot more powerful. ',
    brand: 'Apple',
    productCategory: 'Electornics',
    price: 1099.99,
    stockCount: 64,
    isDeleted: 0,
    modelNumber: 'MGN73LL/A',
    sku: '6200722',
    releaseYear: 2020,
    dateCreated: '2021-11-17T08:00:00.000Z',
    color: 'Space Gray',
    colorFamily: 'Gray',
    weight: 2.8,
    dimensions: '0.63  x 11.97  x 8.36 ',
    screenSize: 13.3,
    screenResolution: '2560 x 1600 ',
    displayType: 'LED',
    touchScreen: 0,
    processorBrand: 'Apple',
    processorModel: 'Apple M1',
    processorModelNumber: 'Apple M1',
    storageType: 'SSD',
    storageCapacity: 512,
    systemMemory: 8,
    graphicsType: 'Integrated',
    graphicsBrand: 'Apple',
    graphicsModel: 'Apple M1',
    operatingSystem: 'macOS Big Sur 11.0',
    voiceAssistant: 'Siri',
    batteryType: 'Lithium-polymer',
    backlitKeyboard: 1,
    reviewCount: 20,
    rating: 4.55,
    starOne: 2,
    starTwo: 0,
    starThree: 0,
    starFour: 1,
    starFive: 17
  },
  {
    productId: 37,
    title:
      'ASUS - ROG 13.4" Touchscreen Gaming Laptop - AMD Ryzen 9 - 16GB Memory - NVIDIA RTX3050 Ti V4G Graphics - 1TB SSD - OFF BLACK - OFF BLACK',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6452/6452915_sd.jpg;maxHeight=300;maxWidth=450',
    description:
      'ASUS ROG Gaming Laptop. Enjoy everyday gaming with this ASUS notebook PC. The AMD Ryzen 9 processor and 16GB of RAM let you run graphics-heavy games smoothly, while the potent NVIDIA RTX3050 Ti V4G graphics produce high-quality visuals on the 13.4-inch WUXGA Touchscreen display. This ASUS notebook PC has 1TD SSD that shortens load times and offers ample storage.\n',
    brand: 'ASUS',
    productCategory: 'Electornics',
    price: 1499.99,
    stockCount: 84,
    isDeleted: 0,
    modelNumber: 'GV301QE-211.ZG13',
    sku: '6452915',
    releaseYear: 2021,
    dateCreated: '2021-11-20T08:00:00.000Z',
    color: 'Off Black',
    colorFamily: 'Black',
    weight: 3.64,
    dimensions: '0.62  x 8.74  x 11.77 ',
    screenSize: 13.4,
    screenResolution: '1920 x 1200',
    displayType: 'IPS',
    touchScreen: 1,
    processorBrand: 'AMD',
    processorModel: 'AMD Ryzen 9',
    processorModelNumber: 'AMD Ryzen 9 5900HS',
    storageType: 'SSD',
    storageCapacity: 1000,
    systemMemory: 16,
    graphicsType: 'Dedicated',
    graphicsBrand: 'NVIDIA',
    graphicsModel: 'NVIDIA GeForce RTX 3050 Ti',
    operatingSystem: 'Windows 11 Home',
    voiceAssistant: 'No',
    batteryType: 'Lithium-ion',
    backlitKeyboard: 1,
    reviewCount: 20,
    rating: 4.75,
    starOne: 0,
    starTwo: 0,
    starThree: 1,
    starFour: 3,
    starFive: 16
  },
  {
    productId: 40,
    title:
      'MSI - GS76 17.3" FHD 360hz Gaming Laptop - Intel Core i9 - NVIDIA GeForce RTX 3070 - 1TB SSD - 32GB Memory',
    image:
      'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6466/6466865_sd.jpg;maxHeight=300;maxWidth=450',
    description:
      'Edge ahead of the pack with this MSI Stealth gaming laptop. The NVIDIA GeForce RTX 3070 graphics card delivers stutter-free, paired with FHD 360hz refresh 3ms screen for fluid gameplay, while the Intel Core i9 processor and 32GB of RAM power through resource-intensive titles. Featuring a 1TB SSD, this MSI Stealth gaming laptop offers ample storage for your files and ultrafast startups.\n',
    brand: 'MSI',
    productCategory: 'Electornics',
    price: 2199.99,
    stockCount: 53,
    isDeleted: 0,
    modelNumber: 'GS7611257',
    sku: '6466865',
    releaseYear: 2021,
    dateCreated: '2021-11-23T08:00:00.000Z',
    color: 'Black',
    colorFamily: 'Black',
    weight: 5.07,
    dimensions: '0.9  x 10.04  x 14.31 ',
    screenSize: 17.3,
    screenResolution: '1920 x 1080 ',
    displayType: 'LED',
    touchScreen: 0,
    processorBrand: 'Intel',
    processorModel: 'Intel 11th Gen Core i9',
    processorModelNumber: '11900H',
    storageType: 'SSD',
    storageCapacity: 1000,
    systemMemory: 32,
    graphicsType: 'Dedicated',
    graphicsBrand: 'NVIDIA',
    graphicsModel: 'NVIDIA GeForce RTX 3070',
    operatingSystem: 'Windows 10',
    voiceAssistant: 'Apple Siri',
    batteryType: 'Lithium-ion polymer',
    backlitKeyboard: 1,
    reviewCount: 20,
    rating: 4.65,
    starOne: 0,
    starTwo: 0,
    starThree: 2,
    starFour: 3,
    starFive: 15
  }
];
