export const QUESTION_ASK_REQUEST = 'QUESTION_ASK_REQUEST';
export const QUESTION_ASK_SUCCESS = 'QUESTION_ASK_SUCCESS';
export const QUESTION_ASK_FAIL = 'QUESTION_ASK_FAIL';
export const QUESTION_ASK_RESET = 'QUESTION_ASK_RESET';


export const QUESTION_AND_ANSWERS_LIST_REQUEST = 'QUESTION_AND_ANSWERS_LIST_REQUEST';
export const QUESTION_AND_ANSWERS_LIST_SUCCESS = 'QUESTION_AND_ANSWERS_LIST_SUCCESS';
export const QUESTION_AND_ANSWERS_LIST_FAIL = 'QUESTION_AND_ANSWERS_LIST_FAIL';
export const QUESTION_AND_ANSWERS_LIST_RESET = 'QUESTION_AND_ANSWERS_LIST_RESET';

