export const QUESTION_ASK_REQUEST = 'QUESTION_ASK_REQUEST';
export const QUESTION_ASK_SUCCESS = 'QUESTION_ASK_SUCCESS';
export const QUESTION_ASK_FAIL = 'QUESTION_ASK_FAIL';
export const QUESTION_ASK_RESET = 'QUESTION_ASK_RESET';

export const QUESTION_AND_ANSWERS_LIST_REQUEST = 'QUESTION_AND_ANSWERS_LIST_REQUEST';
export const QUESTION_AND_ANSWERS_LIST_SUCCESS = 'QUESTION_AND_ANSWERS_LIST_SUCCESS';
export const QUESTION_AND_ANSWERS_LIST_FAIL = 'QUESTION_AND_ANSWERS_LIST_FAIL';
export const QUESTION_AND_ANSWERS_LIST_RESET = 'QUESTION_AND_ANSWERS_LIST_RESET';

export const QUESTION_EDIT_REQUEST = 'QUESTION_EDIT_REQUEST';
export const QUESTION_EDIT_SUCCESS = 'QUESTION_EDIT_SUCCESS';
export const QUESTION_EDIT_FAIL = 'QUESTION_EDIT_FAIL';
export const QUESTION_EDIT_RESET = 'QUESTION_EDIT_RESET';

export const QUESTION_DELETE_REQUEST = 'QUESTION_DELETE_REQUEST';
export const QUESTION_DELETE_SUCCESS = 'QUESTION_DELETE_SUCCESS';
export const QUESTION_DELETE_FAIL = 'QUESTION_DELETE_FAIL';
export const QUESTION_DELETE_RESET = 'QUESTION_DELETE_RESET';

export const QUESTION_VOTE_REQUEST = 'QUESTION_VOTE_REQUEST';
export const QUESTION_VOTE_SUCCESS = 'QUESTION_VOTE_SUCCESS';
export const QUESTION_VOTE_FAIL = 'QUESTION_VOTE_FAIL';

export const ANSWER_CREATE_REQUEST = 'ANSWER_CREATE_REQUEST';
export const ANSWER_CREATE_SUCCESS = 'ANSWER_CREATE_SUCCESS';
export const ANSWER_CREATE_FAIL = 'ANSWER_CREATE_FAIL';
export const ANSWER_CREATE_RESET = 'ANSWER_CREATE_RESET';

export const ANSWER_EDIT_REQUEST = 'ANSWER_EDIT_REQUEST';
export const ANSWER_EDIT_SUCCESS = 'ANSWER_EDIT_SUCCESS';
export const ANSWER_EDIT_FAIL = 'ANSWER_EDIT_FAIL';
export const ANSWER_EDIT_RESET = 'ANSWER_EDIT_RESET';

export const ANSWER_DELETE_REQUEST = 'ANSWER_DELETE_REQUEST';
export const ANSWER_DELETE_SUCCESS = 'ANSWER_DELETE_SUCCESS';
export const ANSWER_DELETE_FAIL = 'ANSWER_DELETE_FAIL';
export const ANSWER_DELETE_RESET = 'ANSWER_DELETE_RESET';
