export const WISH_LIST_ADD_REQUEST = 'WISH_LIST_ADD_REQUEST';
export const WISH_LIST_ADD_SUCCESS = 'WISH_LIST_ADD_SUCCESS';
export const WISH_LIST_ADD_FAIL = 'WISH_LIST_ADD_FAIL';
export const WISH_LIST_ADD_RESET = 'WISH_LIST_ADD_RESET';

export const WISH_ITEMS_LIST_REQUEST = 'WISH_ITEMS_LIST_REQUEST';
export const WISH_ITEMS_LIST_SUCCESS = 'WISH_ITEMS_LIST_SUCCESS';
export const WISH_ITEMS_LIST_FAIL = 'WISH_ITEMS_LIST_FAIL';
export const WISH_ITEMS_LIST_RESET = 'WISH_ITEMS_LIST_RESET';

export const WISH_LIST_DELETE_REQUEST = 'WISH_LIST_DELETE_REQUEST';
export const WISH_LIST_DELETE_SUCCESS = 'WISH_LIST_DELETE_SUCCESS';
export const WISH_LIST_DELETE_FAIL = 'WISH_LIST_DELETE_FAIL';
export const WISH_LIST_DELETE_RESET = 'WISH_LIST_DELETE_RESET';