export const WISH_LIST_ADD_REQUEST = 'WISH_LIST_ADD_REQUEST';
export const WISH_LIST_ADD_SUCCESS = 'WISH_LIST_ADD_SUCCESS';
export const WISH_LIST_ADD_FAIL = 'WISH_LIST_ADD_FAIL';
export const WISH_LIST_ADD_RESET = 'WISH_LIST_ADD_RESET';
